### ISSUE TITLE
[BUG][13.0] purchase_order_secondary_unit: Error when selecting sec. uom without selected product

### ISSUE THREAD

**Issue by gaikaz** [OCA/purchase-workflow#1053]
Affected versions: 13.0 (probably others too)
Possibly same issue could happen with Sales adaptation too.

Steps to reproduce:
1. Create a new Purchase Order
2. Select "Add a product"
3. Before selecting product, try selecting the secondary unit

<details>
<summary>Error from Runbot</summary>
```
Odoo Server Error
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1327, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/dependencies/product-attribute/product_secondary_unit/models/product_second_unit.py", line 45, in name_search
    units = self.search([("code", "=", name)] + args, limit=1)
  File "/.repo_requirements/odoo/odoo/models.py", line 1643, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/.repo_requirements/odoo/odoo/models.py", line 4474, in _search
    query = self._where_calc(args)
  File "/.repo_requirements/odoo/odoo/models.py", line 4194, in _where_calc
    e = expression.expression(domain, self)
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 677, in __init__
    self.parse()
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 909, in parse
    right_ids = comodel.with_context(active_test=False).search([('.'.join(path[1:]), operator, right)], order='id').ids
  File "/.repo_requirements/odoo/odoo/models.py", line 1643, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/.repo_requirements/odoo/odoo/models.py", line 4474, in _search
    query = self._where_calc(args)
  File "/.repo_requirements/odoo/odoo/models.py", line 4194, in _where_calc
    e = expression.expression(domain, self)
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 677, in __init__
    self.parse()
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 976, in parse
    ids1 = select_from_where(cr, field.inverse_name, comodel._table, 'id', ids2, operator)
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 454, in select_from_where
    (select_field, from_table, where_field), (tuple(subids),))
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: operator does not exist: integer = boolean
LINE 1: ...roduct_tmpl_id" FROM "product_product" WHERE "id" IN (false)
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```
</details>

Video from OCA Runbot:

https://user-images.githubusercontent.com/17097810/102887067-e5537a80-445e-11eb-8793-1ad158ac0da2.mp4

**Comment by kittiu** [comment]
Fixed here, https://github.com/OCA/purchase-workflow/pull/1074
Please review.
