### ISSUE TITLE
[12.0] purchase_allowed_product: client error when clicking the product in invoice line modal

### ISSUE THREAD

**Issue by yostashiro** [OCA/purchase-workflow#1083]
How to reproduce:

1. Install purchase_allowed_product
2. Open a customer invoice
3. Click a line to open the modal, and then click on the product

```
Error:
Uncaught Error: KeyError: 'use_only_supplied_product'

http://3460955-12-0-bc3b5b.runbot2-2.odoo-community.org/web/content/578-0bce17a/web.assets_backend.js:402
Traceback:
Error: KeyError: 'use_only_supplied_product'
    at F.__getitem__ (http://3460955-12-0-bc3b5b.runbot2-2.odoo-community.org/web/content/578-0bce17a/web.assets_backend.js:402:161)
    at F.__getattr__ (http://3460955-12-0-bc3b5b.runbot2-2.odoo-community.org/web/content/578-0bce17a/web.assets_backend.js:403:69)
    at F.__getattribute__ (http://3460955-12-0-bc3b5b.runbot2-2.odoo-community.org/web/content/578-0bce17a/web.assets_backend.js:204:38)
    at Object.py.PY_getAttr (http://3460955-12-0-bc3b5b.runbot2-2.odoo-community.org/web/content/578-0bce17a/web.assets_backend.js:168:176)
    at Object.py.evaluate (http://3460955-12-0-bc3b5b.runbot2-2.odoo-community.org/web/content/578-0bce17a/web.assets_backend.js:272:11)
    at Object.py.evaluate (http://3460955-12-0-bc3b5b.runbot2-2.odoo-community.org/web/content/578-0bce17a/web.assets_backend.js:270:194)
    at Object.py.eval (http://3460955-12-0-bc3b5b.runbot2-2.odoo-community.org/web/content/578-0bce17a/web.assets_backend.js:274:284)
    at http://3460955-12-0-bc3b5b.runbot2-2.odoo-community.org/web/content/578-0bce17a/web.assets_backend.js:410:110
    at iterator (http://3460955-12-0-bc3b5b.runbot2-2.odoo-community.org/web/content/572-a7aa12e/web.assets_common.js:14:183)
    at Function.<anonymous> (http://3460955-12-0-bc3b5b.runbot2-2.odoo-community.org/web/content/572-a7aa12e/web.assets_common.js:17:8)
```

The issue is only on the customer invoice. Vendor bills are fine.

**Comment by HviorForgeFlow** [comment]
Tested locally installing purchase_allowed_product module + Invoice app and it is not failing. There must be another module that is triggering this error.
