### ISSUE TITLE
[14.0] purchase_discount : Error when creating invoice from PO if module is installed

### ISSUE THREAD

**Issue by Alliasys** [OCA/purchase-workflow#1101]
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1733, in run
    result = action.run()
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions.py", line 629, in run
    res = runner(run_self, eval_context=eval_context)
  File "/odoo/odoo-server/addons/website/models/ir_actions.py", line 61, in _run_action_code_multi
    res = super(ServerAction, self)._run_action_code_multi(eval_context)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions.py", line 498, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/odoo/odoo-server/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: <class 'TypeError'>: "_prepare_account_move_line() missing 1 required positional argument: 'move'" while evaluating
'if records:\n                action = records.action_create_invoice()'

**Comment by bodedra** [comment]
I can not reproduce it on runbot. It seems issue come from other custom module.

Here is my test:

- Supplier discount configuration on product level

![Screenshot from 2021-02-09 13-54-38](https://user-images.githubusercontent.com/14229503/107427571-ce381d00-6ade-11eb-9056-4f943774c9da.png)

- Created PO and received it.

![Screenshot from 2021-02-09 13-53-20](https://user-images.githubusercontent.com/14229503/107427618-dbeda280-6ade-11eb-8420-cc77a2fea14d.png)

- Create vendor bill.

![Screenshot from 2021-02-09 13-53-15](https://user-images.githubusercontent.com/14229503/107427674-ea3bbe80-6ade-11eb-9490-7927f113dbe2.png)
