### ISSUE TITLE
KeyError: 'product_tmpl_id'

### ISSUE THREAD

**Issue by Hermut** [OCA/purchase-workflow#1155]
Our app have conflict with purchase_discount module. 

The method 'create' rewritten for the model 'product.supplierinfo' in that module considers that the field 'product_tmpl_id' is always in received values, while our app supports values without that parameter. Actually, it also seems that this line is also not used (it is fully redefined 2 lines below without a use). At least, a good practice is to check whether a dict contains a value before applying to that variable (dict["key"] is worse than dict.get("key") in the most cases)

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/sprintit/vendor_product_management/wizard/vendor_import_wizard.py", line 55, in action_import
    results, errors = self._process_import()
  File "/opt/odoo/addons/sprintit/vendor_product_management/wizard/vendor_product_import.py", line 166, in _process_import
    supplier_info_id = supplier_info.create(supplier_info_vals).id
  File "<decorator-gen-215>", line 2, in create
  File "/opt/odoo/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/addons/sprintit/purchase_discount/models/product_supplierinfo.py", line 31, in create
    product_tmpl_id = vals["product_tmpl_id"]
KeyError: 'product_tmpl_id'

**Comment by pedrobaeza** [comment]
You can propose a PR solving the incompatibility without losing any feature.

**Comment by Hermut** [comment]
/models/product_supplierinfo.py line 31 

---     product_tmpl_id = vals["product_tmpl_id"]
+++  product_tmpl_id = vals.get("product_tmpl_id")

**Comment by HviorForgeFlow** [comment]
> /models/product_supplierinfo.py line 31
> 
> --- product_tmpl_id = vals["product_tmpl_id"]
> +++ product_tmpl_id = vals.get("product_tmpl_id")

Go ahead with this proposal with a PR

:crossed_swords:

**Comment by HviorForgeFlow** [comment]
> > /models/product_supplierinfo.py line 31
> > --- product_tmpl_id = vals["product_tmpl_id"]
> > +++ product_tmpl_id = vals.get("product_tmpl_id")
> 
> Go ahead with this proposal with a PR

ping @Hermut

**Comment by Zar-SW** [comment]
I`ve created a PR with a fix.
https://github.com/OCA/purchase-workflow/pull/1161

**Comment by pedrobaeza** [comment]
Finally fixed in #1222
