### ISSUE TITLE
Error in installing the podule purchase_tier-validation

### ISSUE THREAD

**Issue by inventaindia** [OCA/purchase-workflow#1217]
module: purchase_tier_validation
version: 14.0

**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**

**Comment by inventaindia** [comment]
Error:


Traceback:
Error: QWeb2: Template 'tier.review.Collapse' not found
    at Object.exception (http://sap.inventa.in:8069/web/content/15746-7d69966/web.assets_common.js:4384:7)
    at Engine._render (http://sap.inventa.in:8069/web/content/15746-7d69966/web.assets_common.js:4429:103)
    at Engine.render (http://sap.inventa.in:8069/web/content/15746-7d69966/web.assets_common.js:4425:151)
    at Class.renderElement (http://sap.inventa.in:8069/web/content/15746-7d69966/web.assets_common.js:4953:775)
    at http://sap.inventa.in:8069/web/content/15746-7d69966/web.assets_common.js:4963:6

**Comment by legalsylvain** [comment]
nice issue title ! ;-)
