### ISSUE TITLE
[14.0][purchase_order_uninvoiced_amount --> ERROR with notes or sections in PO]

### ISSUE THREAD

**Issue by Mat-moran** [OCA/purchase-workflow#1224]
Hi, 

the purchase_order_uninvoiced_amount is incompatible with notes or sections in purchases orders. 

Reviewing the code I noted that there is not distintion by line type when the `amount_uninvoiced` is calculated and when iterate over a line that is a note or a section it crash.

Which is the best approach to fix that, a filter before start to iterate over the `order.order_line` or another condition inside the iteration process to avoid calculation if the line is note or section?

The error you got when use a note line in a purchase order line is the next one:

> Error:
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 355, in checked_call
    self._cr.precommit.run()
  File "/opt/odoo/custom/src/odoo/odoo/tools/misc.py", line 1148, in run
    func()
  File "/opt/odoo/custom/src/odoo/addons/mail/models/mail_thread.py", line 550, in _finalize_tracking
    tracking = records.with_context(context).message_track(fnames, initial_values)
  File "/opt/odoo/custom/src/odoo/addons/mail/models/mail_thread.py", line 611, in message_track
    tracking[record.id] = record._message_track(tracked_fields, initial_values[record.id])
  File "/opt/odoo/custom/src/odoo/addons/mail/models/mail_thread.py", line 641, in _message_track
    return self._mail_track(tracked_fields, initial)
  File "/opt/odoo/custom/src/odoo/addons/mail/models/models.py", line 40, in _mail_track
    new_value = self[col_name]
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5666, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1019, in __get__
    self.compute_value(recs)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/custom/src/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4061, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo/auto/addons/purchase_order_uninvoiced_amount/models/purchase_order.py", line 32, in _compute_amount_uninvoiced
    if float_compare(qty, 0.0, precision_rounding=rounding) <= 0:
  File "/opt/odoo/custom/src/odoo/odoo/tools/float_utils.py", line 155, in float_compare
    rounding_factor = _float_check_precision(precision_digits=precision_digits,
  File "/opt/odoo/custom/src/odoo/odoo/tools/float_utils.py", line 29, in _float_check_precision
    assert precision_rounding is None or precision_rounding > 0,\
Exception

> The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AssertionError: precision_rounding must be positive, got 0.0 

Thanks and Regards

**Comment by farazbdm** [comment]
this is addressed with the last updates to the module, whereby the float compare and rounding digits comparison condition, has already been removed from the function
@Mat-moran
