### ISSUE TITLE
Error using  OCA / purchase-workflow - Purchase landed costs - Alternative option

### ISSUE THREAD

**Issue by bmessiaz** [OCA/purchase-workflow#1248]
Hi guys,
 
             I´m trying to use this alternative option, howerver I found out the following error.
             Could you please provide me with a full documentation/Manual?
             
             Seems to be  GREAT MODULE, but I need to test it out in order to confirm my first impression.

            Thanks in advance for all help.

            Kind regards,

ERROR WHEN I TRY TO CLICK ON SUPPLIER INVOICE LINE

![image](https://user-images.githubusercontent.com/44352660/130358396-d1cfc9a1-4a5f-4037-884a-28378ad327fb.png)

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1339, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 1740, in name_search
    return self._name_search(name, args, operator, limit=limit)
  File "/home/odoo/src/odoo/odoo/models.py", line 1752, in _name_search
    ids = self._search(args, limit=limit, access_rights_uid=name_get_uid)
  File "/home/odoo/src/odoo/odoo/models.py", line 4481, in _search
    query = self._where_calc(args)
  File "/home/odoo/src/odoo/odoo/models.py", line 4201, in _where_calc
    e = expression.expression(domain, self)
  File "/home/odoo/src/odoo/odoo/osv/expression.py", line 681, in __init__
    self.parse()
  File "/home/odoo/src/odoo/odoo/osv/expression.py", line 862, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'invoice_id.type' in leaf "<osv.ExtendedLeaf: ('invoice_id.type', '=', 'in_invoice') on account_move_line (ctx: )>"

ERROR WHEN I TRY TO ADD A LINE IN EXPENSE LINE FIELD 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1339, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 6251, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/odoo/src/odoo/odoo/models.py", line 6030, in _onchange_eval
    method_res = method(self)
  File "/home/odoo/src/user/OCA/purchase-workflow/purchase_landed_cost/models/purchase_cost_distribution.py", line 597, in onchange_invoice_line
    self.invoice_id = self.invoice_line.invoice_id.id
AttributeError: 'account.move.line' object has no attribute 'invoice_id'

FULL PICTURE OF MY TESTING.

![image](https://user-images.githubusercontent.com/44352660/130358670-e08a78c5-5933-44d4-89a1-9ea23d85cac8.png)

I DIDN´T SEE THE POSTING OF THE 50 EUROS ADDITIONAL LANDED COSTS.

![image](https://user-images.githubusercontent.com/44352660/130358728-916963dc-3c6b-49d4-99b9-5f6b9dae578b.png)

I DIDN´T SEE THE POSTING OF THIS NEW LC INTO THE STOCK MOVES, UPDATING THE UNIT PRICE.

![image](https://user-images.githubusercontent.com/44352660/130358788-77f42879-6dd9-4999-8ef3-fd9576b39f71.png)

FROM ACCOUNTING PERSPECTIVE I SHOULD SEE THE BILL FROM THIS LANDED COST INTO MY ACCOUNTS PAYABLE OVERVIEW.

![image](https://user-images.githubusercontent.com/44352660/130358843-5150e2af-5bdd-4cff-9df2-340bde477779.png)

**Comment by pedrobaeza** [comment]
Fixed in 829f7db30690fb38e40a0ce01b98292ae2e23496

Thanks for reporting.
