### ISSUE TITLE
[13.0] purchase_last_price_info produce an error printing "Product Label (PDF)"

### ISSUE THREAD

**Issue by inprbau** [OCA/purchase-workflow#1389]
We have the same error on two types of installations: a multicompany installation and a single company installation when the purchase_last_price_info module is installed.

**_SINGLE COMPANY INSTALLATION_**
1. The purchase_last_price_info module is installed
2. We have a product that has not been purchased and the module fields are not filled in
![image](https://user-images.githubusercontent.com/50661813/159688228-a409a77c-cc7f-41cf-86c7-d37a311905af.png)
3. When we print the "Product Label (PDF)" of the article the following error appears
![image](https://user-images.githubusercontent.com/50661813/159688857-a6f75c57-f0b4-4163-84d6-e6f2765ee194.png)

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo130/src/core/odoo/models.py", line 5124, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_product_report_simple_label_799
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_qweb.py", line 382, in _get_field
    content = converter.record_to_html(record, field_name, field_options)
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_qweb_fields.py", line 465, in record_to_html
    return super(MonetaryConverter, self).record_to_html(record, field_name, options)
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_qweb_fields.py", line 129, in record_to_html
    return False if value is False else record.env[self._name].value_to_html(value, options=options)
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_qweb_fields.py", line 435, in value_to_html
    formatted_amount = lang.format(fmt, display_currency.round(value),
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/res_currency.py", line 133, in round
    self.ensure_one()
  File "/opt/odoo/odoo130/src/core/odoo/models.py", line 5127, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.currency()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo130/src/core/addons/web/controllers/main.py", line 2049, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/opt/odoo/odoo130/src/core/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo130/src/reporting-engine/report_xlsx_helper/controllers/main.py", line 56, in report_routes
    reportname, docids, converter, **data
  File "/opt/odoo/odoo130/src/core/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo130/src/reporting-engine/report_xlsx/controllers/main.py", line 20, in report_routes
    reportname, docids, converter, **data
  File "/opt/odoo/odoo130/src/core/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo130/src/core/addons/web/controllers/main.py", line 1987, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo/odoo130/src/mis-builder/mis_builder/report/mis_report_instance_qweb.py", line 28, in render_qweb_pdf
    return super(Report, self).render_qweb_pdf(res_ids, data)
  File "/opt/odoo/odoo130/src/core/addons/account/models/ir_actions_report.py", line 50, in render_qweb_pdf
    return super().render_qweb_pdf(res_ids=res_ids, data=data)
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_actions_report.py", line 771, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/opt/odoo/odoo130/src/account-financial-reporting/account_financial_report/models/ir_actions_report.py", line 19, in render_qweb_html
    return super(IrActionsReport, obj).render_qweb_html(docids, data)
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_actions_report.py", line 812, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_actions_report.py", line 551, in render_template
    return view_obj.render_template(template, values)
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_ui_view.py", line 1191, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo/odoo130/src/core/addons/website/models/ir_ui_view.py", line 344, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo/odoo130/src/core/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_ui_view.py", line 1199, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_product_report_producttemplatelabel_795
  File "<template>", line 2, in body_call_content_793
  File "<template>", line 4, in foreach_792
  File "<template>", line 5, in foreach_791
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/qweb.py", line 340, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: Expected singleton: res.currency()
Traceback (most recent call last):
  File "/opt/odoo/odoo130/src/core/odoo/models.py", line 5124, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_product_report_simple_label_799
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_qweb.py", line 382, in _get_field
    content = converter.record_to_html(record, field_name, field_options)
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_qweb_fields.py", line 465, in record_to_html
    return super(MonetaryConverter, self).record_to_html(record, field_name, options)
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_qweb_fields.py", line 129, in record_to_html
    return False if value is False else record.env[self._name].value_to_html(value, options=options)
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/ir_qweb_fields.py", line 435, in value_to_html
    formatted_amount = lang.format(fmt, display_currency.round(value),
  File "/opt/odoo/odoo130/src/core/odoo/addons/base/models/res_currency.py", line 133, in round
    self.ensure_one()
  File "/opt/odoo/odoo130/src/core/odoo/models.py", line 5127, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.currency()

Error to render compiling AST
ValueError: Expected singleton: res.currency()
Template: product.report_simple_label
Path: /t/div/table/tr[2]/td/strong[2]
Node: "<"strong t-field="product.lst_price" t-options="{'widget': 'monetary', 'display_currency': product.company_id.currency_id}"/">"

**_MULTICOMPANY INSTALLATION_**
1. We have a product that has to be available in both companies. 
![image](https://user-images.githubusercontent.com/50661813/159691064-77e2249e-b8ea-4762-ab23-fa0c02699a48.png)
2.  The product that has not been purchased and the module fields are not filled in
![image](https://user-images.githubusercontent.com/50661813/159691536-e5e8c878-7358-45ca-af56-c712f113cee8.png)
3. When we print the "Product Label (PDF)" of the article the same error appears 

**Expected behavior**
The expected behavior is that it generates the pdf of the label. If the module is uninstalled, the labels are printed and the error does not appear.

**Comment by HviorForgeFlow** [comment]
@inprbau can you reproduce the error in a runboat instance? I couldn't, so maybe some customization is colliding the code. But I don't understand why this error is related with purchase_last_price_info because this module is not integrated with print label reports.

**Comment by inprbau** [comment]
@HviorForgeFlow I can't find the runboat instance related to a purchase-workflow (V.13). Could you tell me a valid access?

**Comment by HviorForgeFlow** [comment]
https://runboat.odoo-community.org/webui/builds.html?repo=OCA/purchase-workflow

**Comment by inprbau** [comment]
Reproduced the error: 
http://oca-purchase-workflow-13-0-5fb568b0cbb2.runboat.odoo-community.org/web/login
I have instaled the app of sales.
Go to a product that no have previous purchases: 
![image](https://user-images.githubusercontent.com/50661813/161228781-39e9109f-b428-4ed4-928b-fe87946e90f7.png)
And I try to generat the "product label":
![image](https://user-images.githubusercontent.com/50661813/161229327-bc5bf1cf-465f-42e6-bef8-2784bd4e6164.png)

and.... the error appear:
![image](https://user-images.githubusercontent.com/50661813/161229412-eb172b5e-b5ea-4ca0-97fb-dacfd0577a3d.png)

**Comment by inprbau** [comment]
@HviorForgeFlow sorry, I forgot to mention you in the previous comment

**Comment by inprbau** [comment]
@HviorForgeFlow do you need more information?
