### ISSUE TITLE
[15.0] purchase_order_general_discount installation error

### ISSUE THREAD

**Issue by bigboss97lnt** [OCA/purchase-workflow#1724]
## Module
Purchase Order General Discount

## Describe the bug
When installing the module from apps it shows an error related to an XML file

## To Reproduce
**Affected versions**: Odoo 15 using Odoo.sh

1. Copied the whole package to the repo
2. Install from apps in Odoo
3. Then error shows up

**Expected behavior**
That app gets installed

**Additional context**
Error:
```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 683, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 586, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/odoo/models.py", line 4431, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/odoo/models.py", line 4347, in _load_records_create
    return self.create(values)
  File "<decorator-gen-265>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/addons/website/models/ir_ui_view.py", line 57, in create
    return super().create(vals_list)
  File "<decorator-gen-214>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 394, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/odoo/api.py", line 394, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/enterprise/web_studio/models/studio_mixin.py", line 19, in create
    res = super(StudioMixin, self).create(vals)
  File "<decorator-gen-42>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 412, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 546, in create
    result = super(View, self.with_context(ir_ui_view_partial_validation=True)).create(vals_list)
  File "<decorator-gen-67>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/models.py", line 4079, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/odoo/models.py", line 4244, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/home/odoo/src/odoo/odoo/models.py", line 1367, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 437, in _check_xml
    raise err from None
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in _check_xml
    combined_arch = view._get_combined_arch()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 991, in _get_combined_arch
    arch = root.with_prefetch(tree_views._prefetch_ids)._combine(hierarchy)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 932, in _combine
    combined_arch = view.apply_inheritance_specs(combined_arch, arch)
  File "/home/odoo/src/enterprise/web_studio/models/ir_ui_view.py", line 498, in apply_inheritance_specs
    return super(View, self).apply_inheritance_specs(source, specs_tree,
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 869, in apply_inheritance_specs
    self._raise_view_error(str(e), specs_tree)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 746, in _raise_view_error
    raise err from from_exception
odoo.exceptions.ValidationError: Error while validating view:

Element '<xpath expr="//field[@name=&#39;tax_totals_json&#39;]">' cannot be located in parent view

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1346, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 486, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 603, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 474, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 748, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 814, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 734, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 694, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /home/odoo/src/user/purchase_order_general_discount/views/purchase_order_view.xml:6
Error while validating view:

Element '<xpath expr="//field[@name=&#39;tax_totals_json&#39;]">' cannot be located in parent view

View error context:
{'file': '/home/odoo/src/user/purchase_order_general_discount/views/purchase_order_view.xml',
 'line': 2,
 'name': 'purchase.order form',
 'view': ir.ui.view(3362,),
 'view.model': 'purchase.order',
 'view.parent': ir.ui.view(953,),
 'xmlid': 'purchase_order_form'}
```

**Comment by pedrobaeza** [comment]
You may have other incompatible module in your installation. Have you tried a fresh installation?

**Comment by bigboss97lnt** [comment]
@pedrobaeza that was the case indeed, I had another module with the following code

```
                <xpath expr="//field[@name='tax_totals_json']" position="replace">
                    <field name="amount_untaxed" />
                    <field name="ks_amount_discount" attrs="{'invisible':[('ks_enable_discount','!=',True),('ks_amount_discount','=',0)]}" />
                    <field name="amount_total" />
                </xpath>
```

It was overriding odoo's default fields, I modified the XML in the module then it worked. I will close the ticket

from

```
<?xml version="1.0" encoding="utf-8" ?>
<!-- Copyright 2019 Tecnativa - David Vidal
     License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl). -->
<odoo>

    <record id="purchase_order_form" model="ir.ui.view">
        <field name="model">purchase.order</field>
        <field name="inherit_id" ref="purchase.purchase_order_form" />
        <field name="arch" type="xml">
            <xpath expr="//field[@name='tax_totals_json']" position="before">
                <div class="o_td_label" name="general_discount">
                    <label class="o_form_label" for="general_discount" />
                    <button
                        name="action_update_general_discount"
                        class="oe_link oe_edit_only fa fa-refresh"
                        type="object"
                        help="Update general discounts"
                    />
                </div>
                <field name="general_discount" class="oe_right" nolabel="1" />
            </xpath>
        </field>
    </record>

</odoo>

```

to

```
<?xml version="1.0" encoding="utf-8" ?>
<!-- Copyright 2019 Tecnativa - David Vidal
     License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl). -->
<odoo>

    <record id="purchase_order_form" model="ir.ui.view">
        <field name="model">purchase.order</field>
        <field name="inherit_id" ref="purchase.purchase_order_form" />
        <field name="arch" type="xml">
            <xpath expr="//field[@name='amount_untaxed']" position="before">
                <div class="o_td_label" name="general_discount">
                    <label class="o_form_label" for="general_discount" />
                    <button
                        name="action_update_general_discount"
                        class="oe_link oe_edit_only fa fa-refresh"
                        type="object"
                        help="Update general discounts"
                    />
                </div>
                <field name="general_discount" class="oe_right" nolabel="1" />
            </xpath>
        </field>
    </record>

</odoo>

```
