### ISSUE TITLE
purchase_sign: CI broken.

### ISSUE THREAD

**Issue by legalsylvain** [OCA/purchase-workflow#2415]
Hi all.

I try to make a PR against this repo, and there is an unrelated error in purchase_sign module.

My PR : https://github.com/OCA/purchase-workflow/pull/2171
The issue : https://github.com/OCA/purchase-workflow/actions/runs/11016589474/job/30592466774#step:8:1363

```
2024-09-24 15:11:05,843 487 INFO odoo odoo.addons.purchase_sign.tests.test_purchase_sign: ====================================================================== 
2024-09-24 15:11:05,843 487 ERROR odoo odoo.addons.purchase_sign.tests.test_purchase_sign: ERROR: TestPurchaseSign.test_01_portal_purchase_signature_tour
Traceback (most recent call last):
  File "/opt/odoo/odoo/tests/common.py", line 1163, in _websocket_request
    return f.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/purchase-workflow/purchase-workflow/purchase_sign/tests/test_purchase_sign.py", line 45, in test_01_portal_purchase_signature_tour
    self.start_tour("/", "purchase_signature", login="portal")
  File "/opt/odoo/odoo/tests/common.py", line 1857, in start_tour
    return self.browser_js(url_path=url_path, code=code, ready=ready, **kwargs)
  File "/opt/odoo/odoo/tests/common.py", line 1825, in browser_js
    self.assertTrue(self.browser._wait_ready(ready), 'The ready "%s" code was always falsy' % ready)
  File "/opt/odoo/odoo/tests/common.py", line 1424, in _wait_ready
    result = self._websocket_request('Runtime.evaluate', params={
  File "/opt/odoo/odoo/tests/common.py", line 1165, in _websocket_request
    raise TimeoutError(f'{method}({params or ""})')
TimeoutError: Runtime.evaluate({'expression': "try { odoo.__DEBUG__.services['web_tour.tour'].tours['purchase_signature'].ready } catch {}", 'awaitPromise': True})
 
```

Note : the main branch is red sometime. https://github.com/OCA/purchase-workflow/actions?query=branch%3A16.0

![image](https://github.com/user-attachments/assets/34ea05a7-b85d-437a-8dac-09c41ef9ef5f)

Thanks for your investigation.

CC : @ByteMeAsap

**Comment by legalsylvain** [comment]
Note : CC : @ivantodorovich https://github.com/OCA/pos/issues/1236 /  
@carlos-lopez-tecnativa  : https://github.com/OCA/pos/pull/1226#issuecomment-2360980494

**Comment by pedrobaeza** [comment]
Being handled in https://github.com/OCA/oca-ci/pull/78
