### ISSUE TITLE
[11.0][purchase_landed_cost] error when loading the delivery notes

### ISSUE THREAD

**Issue by rafamarpe** [OCA/purchase-workflow#667]
Hi.
We have tested the module purchase_landed_cost we have created an order with your delivery voucher and then we have generated and validated your invoice.
Then we have created an invoice from another supplier and the product of this invoice we wanted to allocate it on the cost of the articles of the delivery note of the first order.
We have seen in Known issues / Roadmap that indicates Ability to add expenses in multi currency, we have activated multi currency but both the order and the invoice are based on the same currency.
The error it gives is the following:
Error:
Uncaught Error: No conversion for undefined

http://3361082-11-0-c6ae4c.runbot3.odoo-community.org/web/content/555-39ee999/web.assets_backend.js:366
Traceback:
Error: No conversion for undefined
    at wrap (http://3361082-11-0-c6ae4c.runbot3.odoo-community.org/web/content/555-39ee999/web.assets_backend.js:366:44)
    at F.__getitem__ (http://3361082-11-0-c6ae4c.runbot3.odoo-community.org/web/content/555-39ee999/web.assets_backend.js:371:293)
    at Object.py.PY_getItem (http://3361082-11-0-c6ae4c.runbot3.odoo-community.org/web/content/555-39ee999/web.assets_backend.js:183:11)
    at Object.py.evaluate (http://3361082-11-0-c6ae4c.runbot3.odoo-community.org/web/content/555-39ee999/web.assets_backend.js:266:74)
    at Object.py.evaluate (http://3361082-11-0-c6ae4c.runbot3.odoo-community.org/web/content/555-39ee999/web.assets_backend.js:266:88)
    at Object.py.evaluate (http://3361082-11-0-c6ae4c.runbot3.odoo-community.org/web/content/555-39ee999/web.assets_backend.js:265:111)
    at Object.py.evaluate (http://3361082-11-0-c6ae4c.runbot3.odoo-community.org/web/content/555-39ee999/web.assets_backend.js:267:99)
    at Object.py.eval (http://3361082-11-0-c6ae4c.runbot3.odoo-community.org/web/content/555-39ee999/web.assets_backend.js:272:284)
    at http://3361082-11-0-c6ae4c.runbot3.odoo-community.org/web/content/555-39ee999/web.assets_backend.js:380:136
    at Function._.each._.forEach (http://3361082-11-0-c6ae4c.runbot3.odoo-community.org/web/content/549-04f2e05/web.assets_common.js:12:558)

Thanks

**Comment by pedrobaeza** [comment]
An error in frontend is very weird for a backend module. Can you see any log in the server?

**Comment by rafamarpe** [comment]
we have executed it in rubot, we see if we can debug it and give more information
