### ISSUE TITLE
[12.0] purchase_request - cannot cancel PO with multiple lines

### ISSUE THREAD

**Issue by yostashiro** [OCA/purchase-workflow#778]
With this module installed, you cannot cancel a purchase order with multiple lines for this server error:

```
エラー:
Odoo Server Error

Traceback (most recent call last):
  File "/home/ytashiro/ws/hls/odoo/odoo/models.py", line 4718, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ytashiro/ws/hls/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ytashiro/ws/hls/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/ytashiro/ws/hls/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/ytashiro/ws/hls/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/ytashiro/ws/hls/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/ytashiro/ws/hls/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/ytashiro/ws/hls/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/ytashiro/ws/hls/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/ytashiro/ws/hls/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/ytashiro/ws/hls/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/ytashiro/ws/hls/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/ytashiro/ws/hls/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/ytashiro/ws/hls/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/ytashiro/ws/hls/odoo/addons/sale_purchase/models/purchase_order.py", line 12, in button_cancel
    result = super(PurchaseOrder, self).button_cancel()
  File "/home/ytashiro/ws/hls/odoo/addons/purchase_stock/models/purchase.py", line 110, in button_cancel
    order.order_line.write({'move_dest_ids':[(5,0,0)]})
  File "/home/ytashiro/ws/hls/purchase-workflow/purchase_request/models/purchase_order.py", line 197, in write
    prev_qty_received = self.qty_received
  File "/home/ytashiro/ws/hls/odoo/odoo/fields.py", line 979, in __get__
    record.ensure_one()
  File "/home/ytashiro/ws/hls/odoo/odoo/models.py", line 4721, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: purchase.order.line(18, 19, 20)
```

**Comment by HviorForgeFlow** [comment]
Solution proposed here https://github.com/OCA/purchase-workflow/pull/768 , could you review it?

**Comment by yostashiro** [comment]
Fixed by https://github.com/OCA/purchase-workflow/pull/784.
