### ISSUE TITLE
[12.0] purchase_request : traceback when trying to create RFQ with line not approved

### ISSUE THREAD

**Issue by saxomanu** [OCA/purchase-workflow#783]
When trying to make RFQ from not approved request, have a traceback :

```
Odoo Server Error

Traceback (most recent call last):
  File "/home/dev_phyto/odoo/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/dev_phyto/odoo/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/dev_phyto/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/dev_phyto/odoo/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/dev_phyto/odoo/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/dev_phyto/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/dev_phyto/odoo/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/dev_phyto/odoo/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/dev_phyto/odoo/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/dev_phyto/odoo/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/dev_phyto/odoo/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/dev_phyto/odoo/odoo/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/home/dev_phyto/odoo/odoo/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/dev_phyto/odoo/cap_addons/purchase-workflow/purchase_request/wizard/purchase_request_line_make_purchase_order.py", line 106, in default_get
    res['item_ids'] = self.get_items(request_line_ids)
  File "/home/dev_phyto/odoo/cap_addons/purchase-workflow/purchase_request/wizard/purchase_request_line_make_purchase_order.py", line 89, in get_items
    self._check_valid_request_line(request_line_ids)
  File "/home/dev_phyto/odoo/cap_addons/purchase-workflow/purchase_request/wizard/purchase_request_line_make_purchase_order.py", line 49, in _check_valid_request_line
    line.request_id.name)
TypeError: not all arguments converted during string formatting
```

**Comment by HviorForgeFlow** [comment]
@saxomanu I can't reproduce your error on runbot. If purchase request line is not approved it is not possible to use Create RFQ action because a constraint is blocking for non approved lines.

Could you try on runbot? Thanks

**Comment by ovnicraft** [comment]
I confirm that approved is needed to create RFQ.

@saxomanu any news about this ? or can be closed.
