### ISSUE TITLE
[12.0] issue when upgrading purchase_request module

### ISSUE THREAD

**Issue by jjscarafia** [OCA/purchase-workflow#837]
While upgrading a database from v11 to v12 we get the following error:
```
ValueError: Expected singleton: stock.move.line(90487, 90488, 90489, 90490)
2020-01-07 17:41:40,371 97 CRITICAL new-energesa-07-01-1 odoo.service.server: Failed to initialize database `new-energesa-07-01-1`. 
Traceback (most recent call last):
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/models.py", line 4724, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/service/server.py", line 1151, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo-upgrade/base/hooks.py", line 123, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/modules/migration.py", line 190, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/.local/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 1734, in wrapped_function
    if use_env2 else cr, version)
  File "/home/odoo/src/repositories/oca-purchase-workflow/purchase_request/migrations/12.0.1.0.0/post-migration.py", line 138, in migrate
    allocate_stockable(env)
  File "/home/odoo/src/repositories/oca-purchase-workflow/purchase_request/migrations/12.0.1.0.0/post-migration.py", line 91, in allocate_stockable
    alloc_uom, ml_done)
  File "/home/odoo/src/repositories/oca-purchase-workflow/purchase_request/migrations/12.0.1.0.0/post-migration.py", line 34, in allocate_from_stock_move
    to_allocate_qty = ml.product_uom_id._compute_quantity(
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/fields.py", line 1002, in __get__
    record.ensure_one()
  File "/home/odoo/.local/lib/python3.5/site-packages/odoo/models.py", line 4727, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: stock.move.line(90487, 90488, 90489, 90490)

```

This move lines are all from the same move, they are of a product that use lots. So it's a purchase request of 4 units solved with 4 stock.move.line that represents each input for each lot.

We're not familiar to the changes on the models but we believe the issue is that the method "allocate_from_stock_move" [is called with many sml](https://github.com/OCA/purchase-workflow/blob/12.0/purchase_request/migrations/12.0.1.0.0/post-migration.py#L90) but the "allocate_from_stock_move" expects only one (check [here](https://github.com/OCA/purchase-workflow/blob/12.0/purchase_request/migrations/12.0.1.0.0/post-migration.py#L29) and [here](https://github.com/OCA/purchase-workflow/blob/12.0/purchase_request/migrations/12.0.1.0.0/post-migration.py#L34))

**Comment by jjscarafia** [comment]
Hi @AaronHForgeFlow ! Thanks for the migration of this module.
Can you point us on which direction we should go to fix this issue?
Thanks!

**Comment by HviorForgeFlow** [comment]
Fix already merged
