### ISSUE TITLE
[13.0] Error when uninstalling purchase_isolated_rfq

### ISSUE THREAD

**Issue by HviorForgeFlow** [OCA/purchase-workflow#943]
Steps to reproduce:
- Install purchase_isolated_rfq
- Create a RFQ and convert to purchase
- Uninstall purchase_isolated_rfq
- Try to access to Purchase App, next error is shown:
```
Odoo Server Error

Traceback (most recent call last):
  File "/home/hvior/odoo/13.0/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/hvior/odoo/13.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/hvior/odoo/13.0/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/hvior/odoo/13.0/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/hvior/odoo/13.0/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/hvior/odoo/13.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/hvior/odoo/13.0/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/hvior/odoo/13.0/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/hvior/odoo/13.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/hvior/odoo/13.0/addons/web/controllers/main.py", line 1280, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/hvior/odoo/13.0/addons/web/controllers/main.py", line 1299, in do_search_read
    return Model.web_search_read(domain, fields, offset=offset, limit=limit, order=sort)
  File "/home/hvior/odoo/13.0/addons/web/models/models.py", line 39, in web_search_read
    records = self.search_read(domain, fields, offset=offset, limit=limit, order=order)
  File "/home/hvior/odoo/13.0/odoo/models.py", line 4838, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/home/hvior/odoo/13.0/odoo/models.py", line 1618, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/hvior/odoo/13.0/odoo/models.py", line 4383, in _search
    query = self._where_calc(args)
  File "/home/hvior/odoo/13.0/odoo/models.py", line 4112, in _where_calc
    e = expression.expression(domain, self)
  File "/home/hvior/odoo/13.0/odoo/osv/expression.py", line 675, in __init__
    self.parse()
  File "/home/hvior/odoo/13.0/odoo/osv/expression.py", line 856, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'order_sequence' in leaf "<osv.ExtendedLeaf: ('order_sequence', '=', False) on purchase_order (ctx: )>"
```

CC @kittiu @kongrattapong

**Comment by HviorForgeFlow** [comment]
By the way it can be solved updating purchase module

**Comment by kittiu** [comment]
@HviorForgeFlow right, may be we need to write script to clear it during uninstallation. I will check. Thank you for finding.

**Comment by kittiu** [comment]
Fixed provided here, https://github.com/OCA/purchase-workflow/pull/944
