### ISSUE TITLE
[14.0] Purchase Deposit broken in 14 

### ISSUE THREAD

**Issue by kayue** [OCA/purchase-workflow#993]
In Odoo 14, the Purchase Deposit module is broken due to missing access right `ir.model.access`.

```
You are not allowed to access 'Purchase Advance Payment Invoice' (purchase.advance.payment.inv) records.
No group currently allows this operation.
```

![P00044__INV_50962-Consignment__-_Odoo](https://user-images.githubusercontent.com/193112/95599952-58666b00-0a84-11eb-9679-e8979b2b239f.jpg)

And even I am able to grant myself access, I still run into the following error:

```
ValueError: Invalid field 'type' on model 'account.move'

  File "/mnt/extra-addons/purchase_deposit/wizard/purchase_make_invoice_advance.py", line 207, in create_invoices
    self._create_invoice(order, po_line, amount)
  File "/mnt/extra-addons/purchase_deposit/wizard/purchase_make_invoice_advance.py", line 135, in _create_invoice
    "narration": order.notes,
```

```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1363, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/purchase_deposit/wizard/purchase_make_invoice_advance.py", line 207, in create_invoices
    self._create_invoice(order, po_line, amount)
  File "/mnt/extra-addons/purchase_deposit/wizard/purchase_make_invoice_advance.py", line 135, in _create_invoice
    "narration": order.notes,
  File "<decorator-gen-216>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/mnt/extra-addons/common_connector_library/models/account_move.py", line 20, in create
    res = super(AccountMove, self).create(vals)
  File "<decorator-gen-205>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/mnt/extra-addons/hbx_order_address/models/account_move.py", line 22, in create
    res = super().create(vals_list)
  File "<decorator-gen-193>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/purchase/models/account_invoice.py", line 101, in create
    moves = super(AccountMove, self).create(vals_list)
  File "<decorator-gen-165>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 1771, in create
    rslt = super(AccountMove, self).create(vals_list)
  File "<decorator-gen-130>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 262, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_fields.py", line 508, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3784, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'type' on model 'account.move'
```

**Comment by pedrobaeza** [comment]
Which module? There's nothing migrated to 14.0 in this repo, so I close it.

**Comment by kayue** [comment]
@pedrobaeza purchase_deposit module

Just a quick note. `account_move.type` has now been renamed to `account_move.move_type`.

https://github.com/OCA/purchase-workflow/blob/76bdcff0ada9dbbf9352524f5615e0b7c535af84/purchase_deposit/wizard/purchase_make_invoice_advance.py#L107-L111

**Comment by legalsylvain** [comment]
@kayue you can not install V13 (V12 ...) modules on V14 instance. Please port the module and make a PR (following [guidelines](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0)), or pay a partner to do it.

kind regards.
